const exerciseId = "exerciseId";
const name =  "name";
const muscleId = "muscleId";
const pecho = [
    {exerciseId: "m1e1", name: "Press de banca con barra", muscleId: "m1"},
    {exerciseId: "m1e2", name: "Press banca inclinado con mancuernas", muscleId: "m1"},
    {exerciseId: "m1e3", name: "Aperturas en máquina Peck Deck o Contractora", muscleId: "m1"},
    {exerciseId: "m1e4", name: "Cruce de poleas", muscleId: "m1"},
    {exerciseId: "m1e5", name: "Press de banca inclinado con barra", muscleId: "m1"},
    {exerciseId: "m1e6", name: "Press de banca con mancuernas", muscleId: "m1"},
    {exerciseId: "m1e7", name: "Aperturas con mancuernas", muscleId: "m1"},
    {exerciseId: "m1e8", name: "Aperturas inclinadas con mancuernas", muscleId: "m1"},
    {exerciseId: "m1e9", name: "Press de banca en máquina sentado", muscleId: "m1"},
    {exerciseId: "m1e10", name: "Press de banca declinado con barra", muscleId: "m1"},
    {exerciseId: "m1e11", name: "Press de banca declinado con mancuernas", muscleId: "m1"},
    {exerciseId: "m1e12", name: "Flexiones", muscleId: "m1"}
];

const hombros = [
    {exerciseId: "m2e1", name: "Press de hombro con mancuernas", muscleId: "m2"},
    {exerciseId: "m2e2", name: "Elevación lateral con mancuernas", muscleId: "m2"},
    {exerciseId: "m2e3", name: "Elevación frontal con mancuernas", muscleId: "m2"},
    {exerciseId: "m2e4", name: "Cruces inversos en polea alta", muscleId: "m2"},
    {exerciseId: "m2e5", name: "Press de hombros en máquina Smith", muscleId: "m2"},
    {exerciseId: "m2e6", name: "Remo alto con barra", muscleId: "m2"},
    {exerciseId: "m2e7", name: "Elevaciones posteriores para hombros 'Pájaro'", muscleId: "m2"},
    {exerciseId: "m2e8", name: "Elevación lateral con cable a una mano", muscleId: "m2"},
    {exerciseId: "m2e9", name: "Press militar con mancuernas", muscleId: "m2"},
    {exerciseId: "m2e10", name: "Press militar", muscleId: "m2"},
    {exerciseId: "m2e11", name: "Elevaciones frontales con cable a una mano", muscleId: "m2"},
    {exerciseId: "m2e12", name: "Elevaciones frontales con barra", muscleId: "m2"},
    {exerciseId: "m2e13", name: "Press militar sentado con barra", muscleId: "m2"},
    {exerciseId: "m2e14", name: "Press tras nuca sentado", muscleId: "m2"},
    {exerciseId: "m2e15", name: "Press militar de pie", muscleId: "m2"},
    {exerciseId: "m2e16", name: "Press militar de pie tras nuca", muscleId: "m2"},
    {exerciseId: "m2e17", name: "Elevación frontal con mancuernas alternas agarre neutro", muscleId: "m2"},
    {exerciseId: "m2e18", name: "Elevación frontal con un brazo en polea baja agarre neutro", muscleId: "m2"},
    {exerciseId: "m2e19", name: "Elevación frontal con mancuerna a dos manos", muscleId: "m2"}
];

const piernas = [
    {exerciseId: "m3e1", name: "Sentadilla", muscleId: "m3"},
    {exerciseId: "m3e2", name: "Prensa de piernas", muscleId: "m3"},
    {exerciseId: "m3e3", name: "Extensión de piernas", muscleId: "m3"},
    {exerciseId: "m3e4", name: "Zancada", muscleId: "m3"},
    {exerciseId: "m3e5", name: "Curl de pierna tumbado en máquina de femoral", muscleId: "m3"},
    {exerciseId: "m3e6", name: "Sentadilla Hack", muscleId: "m3"},
    {exerciseId: "m3e7", name: "Curl de piernas sentado", muscleId: "m3"},
    {exerciseId: "m3e8", name: "Extensión a una pierna", muscleId: "m3"},
    {exerciseId: "m3e9", name: "Sentadilla frontal", muscleId: "m3"},
    {exerciseId: "m3e10", name: "Peso muerto rumano (piernas rectas) con mancuernas", muscleId: "m3"},
    {exerciseId: "m3e11", name: "Peso muerto rumano (piernas rectas) con barra", muscleId: "m3"},
    {exerciseId: "m3e12", name: "Sentadilla Goblet con mancuerna", muscleId: "m3"},
    {exerciseId: "m3e13", name: "Salto Rodillas al Pecho", muscleId: "m3"},
    {exerciseId: "m3e14", name: "Burpees", muscleId: "m3"},
    {exerciseId: "m3e15", name: "Sentadillas con propio peso", muscleId: "m3"},
    {exerciseId: "m3e16", name: "1.5 repeticiones de sentadillas con propio peso", muscleId: "m3"},
    {exerciseId: "m3e17", name: "Sentadillas con balón medicinal", muscleId: "m3"},
    {exerciseId: "m3e18", name: "Sentadilla búlgara con barra", muscleId: "m3"},
    {exerciseId: "m3e19", name: "Sentadilla búlgara con propio peso", muscleId: "m3"},
    {exerciseId: "m3e20", name: "Sentadilla con mini banda", muscleId: "m3"},
    {exerciseId: "m3e21", name: "Sentadilla con salto", muscleId: "m3"},
    {exerciseId: "m3e22", name: "Sentadilla isométrica apoyado sobre la pared", muscleId: "m3"},
    {exerciseId: "m3e23", name: "Peso muerto con balón medicinal", muscleId: "m3"},
    {exerciseId: "m3e24", name: "Peso muerto a una pierna", muscleId: "m3"},
    {exerciseId: "m3e25", name: "Sentadilla sumo con kettlebell", muscleId: "m3"},
    {exerciseId: "m3e26", name: "Ejercicio 'buenos días' con barra", muscleId: "m3"},
    {exerciseId: "m3e27", name: "Puente con propio peso", muscleId: "m3"},
    {exerciseId: "m3e28", name: "Puentes a una pierna", muscleId: "m3"},
    {exerciseId: "m3e29", name: "Puente con bandas", muscleId: "m3"},
    {exerciseId: "m3e30", name: "Caminata de pato", muscleId: "m3"},
    {exerciseId: "m3e31", name: "Ejercicio Superman en cuadrupedia", muscleId: "m3"},
    {exerciseId: "m3e32", name: "Los Groiners", muscleId: "m3"},
    {exerciseId: "m3e33", name: "Hidrantes", muscleId: "m3"},
    {exerciseId: "m3e34", name: "Elevaciones de cadera con máquina Smith", muscleId: "m3"},
    {exerciseId: "m3e35", name: "Elevaciones de cadera con barra", muscleId: "m3"},
    {exerciseId: "m3e36", name: "Abducciones de cadera sentado con banda", muscleId: "m3"},
    {exerciseId: "m3e37", name: "Abducción de cadera con máquina de abducción de cadera", muscleId: "m3"},
    {exerciseId: "m3e38", name: "Abducción con polea", muscleId: "m3"},
    {exerciseId: "m3e39", name: "Elevaciones en posición de rana con propio peso", muscleId: "m3"},
    {exerciseId: "m3e40", name: "Elevaciones cortas en posición de rana con máquina Smith", muscleId: "m3"},
    {exerciseId: "m3e41", name: "Almejas laterales con banda", muscleId: "m3"},
    {exerciseId: "m3e42", name: "Levantamiento de pierna acostado de lado", muscleId: "m3"},
    {exerciseId: "m3e43", name: "Elevaciones de bíceps femoral con máquina GHD", muscleId: "m3"},
    {exerciseId: "m3e44", name: "Step Up con mancuernas", muscleId: "m3"},
    {exerciseId: "m3e45", name: "Caminata lateral con minibanda", muscleId: "m3"},
    {exerciseId: "m3e46", name: "Elevaciones de rodilla", muscleId: "m3"},
    {exerciseId: "m3e47", name: "Columpios con kettlebell", muscleId: "m3"},
    {exerciseId: "m3e48", name: "Contragolpe con cable", muscleId: "m3"},
    {exerciseId: "m3e49", name: "Patadas de burro", muscleId: "m3"},
    {exerciseId: "m3e50", name: "Elevaciones de cadera acostado lateralmente", muscleId: "m3"},
    {exerciseId: "m3e51", name: "Sentadilla Posturas funcionales", muscleId: "m3"}
];

const triceps = [
    {exerciseId: "m4e1", name: "Extensión de tríceps tumbado", muscleId: "m4"},
    {exerciseId: "m4e2", name: "Extensión de tríceps en polea", muscleId: "m4"},
    {exerciseId: "m4e3", name: "Extensión de tríceps en polea con cuerda", muscleId: "m4"},
    {exerciseId: "m4e4", name: "Extensión de tríceps con mancuernas por encima de la cabeza", muscleId: "m4"},
    {exerciseId: "m4e5", name: "Press banca con agarre cerrado", muscleId: "m4"},
    {exerciseId: "m4e6", name: "Patadas traseras", muscleId: "m4"},
    {exerciseId: "m4e7", name: "Extensión de tríceps con cable de agarre inverso con barra", muscleId: "m4"},
    {exerciseId: "m4e8", name: "Extensión de tríceps con cable a una mano", muscleId: "m4"},
    {exerciseId: "m4e9", name: "Extensión de tríceps con cable a una mano con agarre supinado", muscleId: "m4"},
    {exerciseId: "m4e10", name: "Extensión de tríceps con mancuernas tumbado", muscleId: "m4"},
    {exerciseId: "m4e11", name: "Press francés sentado con barra", muscleId: "m4"},
    {exerciseId: "m4e12", name: "Fondos en banco", muscleId: "m4"},
    {exerciseId: "m4e13", name: "Fondos en barras paralelas", muscleId: "m4"}
];

const biceps = [
    {exerciseId: "m5e1", name: "Curl con barra", muscleId: "m5"},
    {exerciseId: "m5e2", name: "Curl alterno con mancuernas", muscleId: "m5"},
    {exerciseId: "m5e3", name: "Curl con cuerda en polea", muscleId: "m5"},
    {exerciseId: "m5e4", name: "Curl con barra EZ", muscleId: "m5"},
    {exerciseId: "m5e5", name: "Curl de predicador con barra EZ", muscleId: "m5"},
    {exerciseId: "m5e6", name: "Curl alterno de martillo con mancuernas", muscleId: "m5"},
    {exerciseId: "m5e7", name: "Curl inclinado con mancuernas", muscleId: "m5"},
    {exerciseId: "m5e8", name: "Curl concentrado con mancuernas", muscleId: "m5"},
    {exerciseId: "m5e9", name: "Curl de cable en polea baja a una mano", muscleId: "m5"},
    {exerciseId: "m5e10", name: "Curl de cable con barra recta en polea baja", muscleId: "m5"},
    {exerciseId: "m5e11", name: "Curl de cable en polea alta de pie", muscleId: "m5"},
    {exerciseId: "m5e12", name: "Curl de muñeca con barra sentado", muscleId: "m5"},
    {exerciseId: "m5e13", name: "Extensión de muñeca con barra sentado", muscleId: "m5"},
    {exerciseId: "m5e14", name: "Curl de barra invertido", muscleId: "m5"}
];

const espalda = [
    {exerciseId: "m6e1", name: "Remo con mancuerna a una mano", muscleId: "m6"},
    {exerciseId: "m6e2", name: "Jalón con agarre ancho", muscleId: "m6"},
    {exerciseId: "m6e3", name: "Remo en máquina", muscleId: "m6"},
    {exerciseId: "m6e4", name: "Jalón al pecho con agarre cerrado", muscleId: "m6"},
    {exerciseId: "m6e5", name: "Remo con barra", muscleId: "m6"},
    {exerciseId: "m6e6", name: "Jalón tras nuca", muscleId: "m6"},
    {exerciseId: "m6e7", name: "Jalón al pecho con agarre invertido", muscleId: "m6"},
    {exerciseId: "m6e8", name: "Jalón en polea con cuerda", muscleId: "m6"},
    {exerciseId: "m6e9", name: "Remo en barra T", muscleId: "m6"},
    {exerciseId: "m6e10", name: "Remo inclinado con barra con agarre supinado", muscleId: "m6"},
    {exerciseId: "m6e11", name: "Elevaciones en barra fija", muscleId: "m6"},
    {exerciseId: "m6e12", name: "Elevaciones tras nuca en barra fija", muscleId: "m6"},
    {exerciseId: "m6e13", name: "Elevaciones en barra fija con agarre supinado", muscleId: "m6"},
    {exerciseId: "m6e14", name: "Jalón dorsal con brazos rectos", muscleId: "m6"},
    {exerciseId: "m6e15", name: "Remo inclinado con mancuernas", muscleId: "m6"},
    {exerciseId: "m6e16", name: "Pullover con mancuerna", muscleId: "m6"},
    {exerciseId: "m6e17", name: "Pullover con barra", muscleId: "m6"},
    {exerciseId: "m6e18", name: "Peso muerto con barra", muscleId: "m6"},
    {exerciseId: "m6e19", name: "Peso muerto sumo con barra", muscleId: "m6"},
    {exerciseId: "m6e20", name: "Peso muerto con barra hexagonal", muscleId: "m6"},
    {exerciseId: "m6e21", name: "Peso muerto con mancuernas", muscleId: "m6"},
    {exerciseId: "m6e22", name: "Encogimiento de hombros con barra", muscleId: "m6"},
    {exerciseId: "m6e23", name: "Encogimiento de hombros con mancuernas", muscleId: "m6"}
];
