import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:flutter_application_test1/models/MuscleData.dart'; // Ensure this is generated by Amplify
import 'package:flutter_application_test1/domain_layer/entities/core_entities.dart' as domain;

class RealDataRepository {
  Future<List<domain.MuscleData>> fetchAllMuscles() async {
    try {
      // Query the DataStore for all MuscleData items
      List<MuscleData> muscleDataList = await Amplify.DataStore.query(MuscleData.classType);

      // Map the fetched models to the domain entities
      return muscleDataList.map((muscleData) {
        return domain.MuscleData(
          id: muscleData.muscleId,
          name: muscleData.name,
        );
      }).toList();
    } on DataStoreException catch (e) {
      print('Query failed: $e');
      return [];
    }
  }
}
